### PR TITLE
Fix index out of range error in convertLine

### PR DESCRIPTION
**Pull request by natekspencer**
This is a quick fix for https://github.com/SonicRift/Vestaboard/issues/17

### CODE REVIEW

**Review by SonicRift — CHANGES_REQUESTED** [review]
@natekspencer - This looks great! Nice catch in just swapping around the logic.
One final note - please add corresponding tests inside `tests/test_formatting.py` to cover the changes. Once those are added, I will merge!

**Comment by SonicRift** [comment]
@natekspencer - you can just follow the same format as the existing tests. If you've never use Pytest before, just make sure the function name you choose starts with the word `test` and it should auto-run when you next commit/push. You should add both a passing and a failing test case if possible, though just a passing case would also be just fine. Feel free to shoot me a message if you need more info!

**Comment by natekspencer** [comment]
There you go!

**Comment by SonicRift** [comment]
Looks great!! Really nice work. Thanks for the collaboration, @natekspencer!

**Pull request merged**
